replicaCount: 1

image:
  repository: mydeveloperaccount/dockerdemo
  tag: v3

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  hosts:
    host: "kubernetes.docker.internal"
    paths: "/"

environment:
  MESSAGE: "Hello from the helm chart values! Hello you all!"
