replicaCount: 4

image:
  repository: mydeveloperaccount/dockerdemo
  tag: v1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  hosts:
    host: "kubernetes.docker.internal"
    paths: "/"

environment:
  MESSAGE: "Hello from the helm chart values!"
