apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greeting-chart.fullname" . }}-configmap
  labels:
    app: {{ include "greeting-chart.name" . }}
data:
  {{- range $k, $v := .Values.environment }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
