apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "greeting-chart.name" . }}-ingress
  labels:
    app: {{ include "greeting-chart.name" . }}
spec:
  ingressClassName: "nginx"
  rules:
    - host: {{ .Values.ingress.hosts.host }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts.paths }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "greeting-chart.name" . }}-service
                port:
                  number: 80
